mainSections = ["posts", "docs", "blogs"]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
ga_analytics = "UA-130660686-1"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7
codeLineNumbers = false
centerLogo = true

[logo]
  # lightMode = "images/logo.png"
  # darkMode = "images/logo.png"
  centerLogo = true

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/sous-chefs"
