baseURL = "http://sous-chefs.org"
languageCode = "en-us"
title = "Sous Chefs"
publishDir = "docs" 

theme = "hyde-y"
# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.sous-chefs.org"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
# disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Sous Chefs"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Sous Chefs"
    topline = "Collaborative community of Chef practitioners dedicated to improving the quality of cookbooks"
    footline = "code with <i class='fa fa-heart'></i>"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    home = "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "dark"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "sous-chefs"
    rss = false

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
