baseURL = "https://sous-chefs.org/"
languageCode = "en-us"
title = "Sous Chefs"
publishDir = "public"
themesDir = "themes"
theme = "hugo-whisper-theme"

[author]
    name = "Sous Chefs"

# [params]
#     brand = "Sous Chefs"
#     topline = "Collaborative community of Chef practitioners dedicated to improving the quality of cookbooks"
#     homepage_button_link = '/docs'
#     homepage_button_text = 'Read The Docs'


[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  googleAnalytics = "UA-130660686-1"
  mainSections = ["minutes","docs"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Minutes"
    url = "/minutes/"
    weight = 3

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4
