baseURL = "https://sous-chefs.org/"
languageCode = "en-us"
title = "Sous Chefs"
publishDir = "."
theme = "hyde-y"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Sous Chefs"

[params]
    brand = "Sous Chefs"
    topline = "Collaborative community of Chef practitioners dedicated to improving the quality of cookbooks"
    footline = "code with <i class='fa fa-heart'></i>"

    sidebar = "right"
    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "dark"

    # Google Analytics.
    googleAnalytics = "UA-130660686-1"

    # Sidebar social links.
    github = "sous-chefs"
    rss = false

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
