baseURL = "https://sous-chefs.org/"
languageCode = "en-us"
title = "Sous Chefs"
publishDir = "public"
themesDir = "themes"
theme = "hugo-whisper-theme"

[params]
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  google_analytics_id = "UA-130660686-1"
  mainSections = ["minutes","docs"]

  [params.homepage_meta_tags]
    meta_description = "Collaborative community of Chef practitioners dedicated to improving the quality of cookbooks"
    meta_og_title = "Sous-Chefs"
    meta_og_type = "website"
    meta_og_url = "https://sous-chefs.org"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_twitter_site = "@souschefsorg"
    meta_twitter_creator = "@souschefsorg"

[params.logo]
    mobile = "logo.png"
    standard  = "logo.png"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Minutes"
    url = "/minutes/"
    weight = 3

# Uncomment and add a section to mainSections
# when we get posts
# [[menu.main]]
#     name = "Posts"
#     url = "/posts/"
#     weight = 4
